"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "ar" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ar")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage) {
      setLanguageState(savedLanguage)
      document.documentElement.lang = savedLanguage
      document.documentElement.dir = savedLanguage === "ar" ? "rtl" : "ltr"
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
    document.documentElement.lang = lang
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Common
    loading: "جاري التحميل...",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    submit: "إرسال",
    search: "بحث",
    filter: "تصفية",
    close: "إغلاق",
    confirm: "تأكيد",
    yes: "نعم",
    no: "لا",
    actions: "الإجراءات",
    view: "عرض",
    download: "تحميل",
    upload: "رفع",
    send: "إرسال",
    back: "رجوع",
    next: "التالي",
    previous: "السابق",
    select: "اختيار",
    selectAll: "تحديد الكل",
    clear: "مسح",
    reset: "إعادة تعيين",
    apply: "تطبيق",
    create: "إنشاء",
    update: "تحديث",
    remove: "إزالة",

    // Roles
    student: "طالب",
    supervisor: "مشرف",
    coordinator: "منسق",
    admin: "مدير",

    // Sidebar Navigation
    dashboard: "لوحة التحكم",
    myProject: "مشروعي",
    tasks: "المهام",
    meetings: "الاجتماعات",
    files: "الملفات",
    announcements: "الإعلانات",
    discussions: "المناقشات",
    messages: "الرسائل",
    grades: "الدرجات",
    notifications: "الإشعارات",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    profile: "الملف الشخصي",
    projects: "المشاريع",
    students: "الطلاب",
    supervisors: "المشرفين",
    reports: "التقارير",
    archive: "الأرشيف",
    assignSupervisors: "تعيين المشرفين",
    projectIdeas: "أفكار المشاريع",
    evaluations: "التقييمات",
    tasksAndEvaluation: "المهام والتقييم",

    // Platform
    platformTitle: "منصة المشاريع",
    graduationProjectsPlatform: "منصة مشاريع التخرج",
    mainMenu: "القائمة الرئيسية",
    mainNavDescription: "قائمة التنقل الرئيسية للوصول إلى جميع أقسام النظام",

    // Auth Pages
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    forgotPassword: "نسيت كلمة المرور؟",
    resetPassword: "إعادة تعيين كلمة المرور",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    name: "الاسم",
    phone: "رقم الهاتف",
    studentId: "الرقم الجامعي",
    employeeId: "الرقم الوظيفي",
    department: "القسم",
    role: "الدور",
    loginButton: "تسجيل الدخول",
    loggingIn: "جاري تسجيل الدخول...",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",

    // Dashboard
    welcome: "مرحباً",
    welcomeBack: "مرحباً بعودتك",
    overviewText: "إليك نظرة عامة على مشروع التخرج الخاص بك",
    supervisorOverview: "نظرة عامة على المشاريع التي تشرف عليها",
    coordinatorOverview: "نظرة عامة على جميع المشاريع",
    totalTasks: "إجمالي المهام",
    completedTasks: "المهام المكتملة",
    upcomingMeetings: "الاجتماعات القادمة",
    projectProgress: "تقدم المشروع",
    recentTasks: "المهام الأخيرة",
    recentNotifications: "الإشعارات الأخيرة",
    latestUpdates: "آخر التحديثات",
    noTasksYet: "لا توجد مهام حالياً",
    noDataFound: "لم يتم العثور على بيانات المستخدم",
    errorLoadingData: "حدث خطأ أثناء تحميل البيانات",
    errorOccurred: "حدث خطأ",
    welcomeToplatform: "مرحباً بك في المنصة",
    startByAddingProject: "ابدأ بإضافة مشروعك ومتابعة المهام",

    // Project Page
    projectDetails: "تفاصيل مشروع التخرج الخاص بك",
    myProjectDetails: "تفاصيل مشروعي",
    submitProjectIdea: "تقديم فكرة مشروع",
    submittedProjectIdeas: "أفكار المشاريع المقدمة",
    projectIdeasStatus: "حالة أفكار المشاريع التي قدمتها",
    submissionDate: "تاريخ التقديم",
    approved: "مقبول",
    rejected: "مرفوض",
    underReview: "قيد المراجعة",
    noProjectAssigned: "لم يتم تعيين مشروع بعد",
    projectSubmittedUnderReview: "تم تقديم فكرة المشروع وهي قيد المراجعة. سيتم إشعارك بالقرار قريباً.",
    submitOrWait: "قدم فكرة مشروع أو انتظر تعيين مشروع من المنسق الأكاديمي",
    active: "نشط",
    completed: "مكتمل",
    pending: "معلق",
    inProgress: "قيد التنفيذ",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    expectedDeliveryDate: "تاريخ التسليم المتوقع",
    notSpecified: "غير محدد",
    tasksAndAssignments: "التسليمات والواجبات",
    discussionForum: "منتدى النقاش",
    evaluationsAndResults: "التقييمات والنتائج",
    supervisorInfo: "معلومات المشرف على المشروع",
    contactSupervisor: "التواصل مع المشرف",
    projectObjectives: "أهداف المشروع",
    noObjectivesYet: "لم يتم تحديد أهداف بعد",
    projectTitle: "عنوان المشروع",
    projectDescription: "وصف المشروع",
    projectStatus: "حالة المشروع",
    projectType: "نوع المشروع",
    approveRejectProjectIdeasTitle: "الموافقة أو رفض أفكار المشاريع المقدمة من الطلاب",
    ideasWaitingDecision: "أفكار المشاريع المقدمة في انتظار القرار",
    approvedPlural: "المقبولة",
    ideasApproved: "أفكار المشاريع المقبولة",
    rejectedPlural: "المرفوضة",
    ideasRejected: "أفكار المشاريع المرفوضة",
    noIdeasUnderReview: "لا توجد أفكار مشاريع قيد المراجعة حالياً",
    allIdeasReviewed: "تم مراجعة جميع أفكار المشاريع المقدمة",
    noApprovedIdeas: "لا توجد أفكار مشاريع مقبولة حالياً",
    noIdeaApprovedYet: "لم يتم قبول أي فكرة مشروع بعد",
    noRejectedIdeas: "لا توجد أفكار مشاريع مرفوضة حالياً",
    noIdeaRejectedYet: "لم يتم رفض أي فكرة مشروع بعد",
    projectIdeaDetailsDesc: "تفاصيل فكرة المشروع المقدمة من الطالب",
    description: "الوصف",
    notAssignedYet: "لم يتم التعيين بعد",
    approveIdea: "الموافقة على الفكرة",
    rejectIdea: "رفض الفكرة",
    approveAssignSupervisorsTitle: "الموافقة على فكرة المشروع وتعيين المشرفين",
    teamProject: "مشروع جماعي",
    chooseSupervisorsAndDatesDesc: "اختر المشرفين المناسبين وحدد تواريخ البدء والانتهاء للمشروع",
    leader: "القائد",
    supervisorsRequiredMulti: "المشرفون مطلوبون للمشاريع الجماعية",
    primarySupervisor: "المشرف الرئيسي",
    secondarySupervisor: "المشرف الثانوي",
    endDateOptional: "تاريخ الانتهاء (اختياري)",
    approving: "جاري الموافقة...",
    approveAndCreateProject: "الموافقة وإنشاء المشروع",
    rejectProjectIdeaTitle: "رفض فكرة المشروع",
    pleaseExplainRejectionReason: "يرجى شرح سبب رفض فكرة المشروع",
    project: "المشروع",
    rejectionReason: "سبب الرفض",
    writeRejectionReasonPlaceholder: "اكتب سبب الرفض هنا...",
    confirmReject: "هل أنت متأكد من رفض هذه الفكرة؟",
    formProjectTeamTitle: "تشكيل فريق المشروع",
    formTeamDesc: "حدد الطلاب الذين سيشكلون فريق المشروع هذا",
    currentTeamMembers: "أعضاء الفريق الحاليون",
    default: "افتراضي",
    secondary: "ثانوي",
    addStudentToTeam: "إضافة طالب إلى الفريق",
    selectStudentt: "اختر طالباً",
    noAvailableStudents: "لا يوجد طلاب متاحين للانضمام إلى الفريق",

    // Tasks
    taskTitle: "عنوان المهمة",
    taskDescription: "وصف المهمة",
    taskStatus: "حالة المهمة",
    taskPriority: "أولوية المهمة",
    dueDate: "تاريخ الاستحقاق",
    assignedTo: "مسندة إلى",
    assignedBy: "مسندة من",
    new: "جديدة",
    high: "عالية",
    medium: "متوسطة",
    low: "منخفضة",
    urgent: "عاجل",
    addTask: "إضافة مهمة",
    editTask: "تعديل مهمة",
    deleteTask: "حذف مهمة",
    completeTask: "إكمال المهمة",
    markAsComplete: "تعيين كمكتملة",
    markAsIncomplete: "تعيين كغير مكتملة",
    approveRejectProjectIdeasDesc: "راجع أفكار المشاريع المقدمة ووافق عليها أو ارفضها",

    // Meetings
    meetingTitle: "عنوان الاجتماع",
    meetingDescription: "وصف الاجتماع",
    meetingDate: "تاريخ الاجتماع",
    meetingTime: "وقت الاجتماع",
    meetingLocation: "موقع الاجتماع",
    meetingLink: "رابط الاجتماع",
    meetingStatus: "حالة الاجتماع",
    scheduled: "مجدول",
    canceled: "ملغي",
    addMeeting: "إضافة اجتماع",
    editMeeting: "تعديل اجتماع",
    deleteMeeting: "حذف اجتماع",
    joinMeeting: "الانضمام للاجتماع",
    scheduleMeeting: "جدولة اجتماع",
    noMeetingsYet: "لا توجد اجتماعات حالياً",
    upcomingMeeting: "اجتماع قادم",
    pastMeeting: "اجتماع سابق",
    requestMeeting: "طلب اجتماع",
    meetingNotes: "ملاحظات الاجتماع",
    date: "التاريخ",
    time: "الوقت",
    meetingRequests: "طلبات الاجتماع",
    submittedOn: "تم التقديم في",
      teamStatus: "حالة الفريق",
      ideaSubmittedBy: "مقدم الفكرة",
      submittedAt: "تاريخ التقديم",
      waitingTeamFormation: "بانتظار تشكيل الفريق",
      notApprovedYet: "لم يوافق بعد",
      waitingSomeMembersApproval: "بانتظار موافقة بعض الأعضاء",
      teamNotFormed: "لم يتشكل الفريق",
    timeRange: "من 8 صباحاً إلى 8 مساءً",
    meetingsBetweenHours: "يجب أن تكون الاجتماعات بين 8 صباحاً و 8 مساءً",
    fieldRequired: "الرجاء ملء جميع الحقول المطلوبة",
    savedSuccessfully: "تم الحفظ بنجاح",
    errorMessage: "حدث خطأ، يرجى المحاولة مرة أخرى",

    // Archive
    restoreProject: "استرجاع المشروع",
    archived: "مؤرشف",
    archivedProjects: "المشاريع المؤرشفة",
    noArchivedProjects: "لا توجد مشاريع مؤرشفة",
    archivedProjectsDescription: "سيتم عرض المشاريع المؤرشفة هنا",
    projectRestoredSuccessfully: "تم استرجاع المشروع بنجاح",
    errorRestoringProject: "حدث خطأ أثناء استرجاع المشروع",

    // Projects
    allProjects: "جميع المشاريع",
    approveProjects: "الموافقة على المشاريع",
    addProject: "إضافة مشروع",
    editProject: "تعديل مشروع",
    deleteProject: "حذف مشروع",
    viewDetails: "عرض التفاصيل",
    projectProposalDetails: "تفاصيل المشروع المقترح",
    acceptProject: "قبول المشروع",
    rejectProject: "رفض المشروع",
    suspendProject: "تعليق المشروع",
    archiveProject: "أرشفة المشروع",
    projectApprovedSuccessfully: "تم قبول المشروع بنجاح",
    projectRejected: "تم رفض المشروع",
    projectSuspended: "تم تعليق المشروع",
    projectArchived: "تم أرشفة المشروع",
    errorApprovingProject: "حدث خطأ في قبول المشروع",
    errorRejectingProject: "حدث خطأ في رفض المشروع",
    errorSuspendingProject: "حدث خطأ في تعليق المشروع",
    errorArchivingProject: "حدث خطأ في أرشفة المشروع",
    projectAddedSuccessfully: "تم إضافة المشروع بنجاح",
    projectUpdatedSuccessfully: "تم تحديث المشروع بنجاح",
    projectDeletedSuccessfully: "تم حذف المشروع",
    errorAddingProject: "حدث خطأ أثناء إضافة المشروع",
    errorUpdatingProject: "حدث خطأ أثناء تحديث المشروع",
    errorDeletingProject: "حدث خطأ في حذف المشروع",
    errorLoadingProjects: "حدث خطأ في تحميل المشاريع",
    suspended: "معلق",
    progress: "التقدم",
    notAssigned: "غير معين",
    objectives: "الأهداف",
    confirmDelete: "هل أنت متأكد من حذف هذا المشروع؟",
    teamManagement: "إدارة الفريق",
    teamMembers: "أعضاء الفريق",
    addStudentToProject: "إضافة طالب للمشروع",
    removeStudent: "حذف الطالب",
    studentAddedSuccessfully: "تم إضافة الطالب إلى المشروع بنجاح",
    studentRemovedSuccessfully: "تم حذف الطالب من المشروع",
    studentAlreadyHasProject: "هذا الطالب لديه مشروع بالفعل",
    errorAddingStudent: "حدث خطأ أثناء إضافة الطالب",
    errorRemovingStudent: "حدث خطأ أثناء حذف الطالب",
    errorLoadingTeamMembers: "حدث خطأ في تحميل أعضاء الفريق",
    pleaseSelectStudent: "يرجى اختيار طالب",
    ideaDataLoaded: "تم تحميل بيانات الفكرة المقبولة، يرجى اختيار المشرف",
    errorLoadingIdeaData: "حدث خطأ في تحميل بيانات الفكرة",

    // Students
    studentsManagement: "إدارة الطلاب",
    assignSupervisorsDescription: "تعيين المشرفين للطلاب ومتابعة حالتهم",
    addNewStudent: "إضافة طالب جديد",
    totalStudents: "إجمالي الطلاب",
    studentsWithoutSupervisor: "طلاب بدون مشرف",
    studentsWithSupervisor: "طلاب مع مشرف",
    noStudentsYet: "لا يوجد طلاب حالياً",
    studentsWillAppearHere: "سيظهر الطلاب هنا بعد التسجيل",
    studentsList: "قائمة الطلاب",
    allRegisteredStudents: "جميع الطلاب المسجلين في النظام",
    assigned: "تم التعيين",
    withoutSupervisor: "بدون مشرف",
    changeSupervisor: "تغيير المشرف",
    assignSupervisor: "تعيين مشرف",
    selectAppropiateSupervisor: "اختر المشرف المناسب للطالب",
    selectedSupervisor: "المشرف المختار",
    currentStudentCount: "عدد الطلاب الحالي",
    supervisorAssignedSuccessfully: "تم تعيين المشرف بنجاح",
    errorAssigningSupervisor: "حدث خطأ أثناء تعيين المشرف",
    pleaseSelectSupervisor: "يرجى اختيار مشرف",
    fullName: "الاسم الكامل",
    enterFullName: "أدخل الاسم الكامل",
    enterEmail: "أدخل البريد الإلكتروني",
    enterPassword: "أدخل كلمة المرور",
    universityId: "الرقم الجامعي",
    example: "مثال",
    selectDepartment: "اختر القسم",
    noDepartmentsAvailable: "لا توجد أقسام متاحة",
    addDepartmentsFromSettings: "يرجى إضافة أقسام من صفحة إدارة الأقسام",
    selectedDepartment: "القسم المختار",
    phoneNumber: "رقم الهاتف",
    emailAlreadyInUse: "البريد الإلكتروني مستخدم بالفعل",
    errorAddingStudentAccount: "حدث خطأ أثناء إضافة الطالب",
    assign: "تعيين",
    addStudent: "إضافة الطالب",
    enterStudentData: "أدخل بيانات الطالب لإنشاء حساب جديد",

    // Discussions
    shareIdeasWithTeam: "شارك الأفكار والأسئلة مع فريقك",
    newDiscussion: "نقاش جديد",
    createNewDiscussion: "إنشاء نقاش جديد",
    discussionTitle: "عنوان النقاش",
    enterDiscussionTitle: "أدخل عنوان النقاش",
    discussionContent: "محتوى النقاش",
    explainDiscussionInDetail: "اشرح موضوع النقاش بالتفصيل",
    tags: "الوسوم",
    optional: "اختياري",
    tagsExample: "مثال: تقني، تقرير، مراجعة (افصل بفاصلة)",
    separateTagsWithComma: "افصل بين الوسوم بفاصلة",
    createDiscussion: "إنشاء النقاش",
    discussionCreatedSuccessfully: "تم إنشاء النقاش بنجاح",
    errorCreatingDiscussion: "حدث خطأ أثناء إنشاء النقاش",
    errorFetchingDiscussions: "حدث خطأ أثناء تحميل النقاشات",
    all: "الكل",
    open: "مفتوح",
    closed: "مغلق",
    noDiscussions: "لا توجد نقاشات",
    noDiscussionsYet: "لم يتم إنشاء أي نقاشات بعد. ابدأ بإنشاء نقاش جديد.",
    pinned: "مثبت",
    reply: "رد",
    discussionNotFound: "النقاش غير موجود",
    noProject: "لا يوجد مشروع",
    mustBeInProjectForDiscussions: "يجب أن تكون مسجلاً في مشروع للمشاركة في المناقشات",
    mustBeInProjectToCreateDiscussion: "يجب أن يكون لديك مشروع لإنشاء نقاش",
    fewMinutesAgo: "منذ دقائق",
    hoursAgo: "منذ {hours} ساعة",
    oneDayAgo: "منذ يوم واحد",

    // Announcements
    announcementsManagement: "إدارة ونشر الإعلانات العامة لجميع المستخدمين",
    newAnnouncement: "إعلان جديد",
    publishNewAnnouncement: "نشر إعلان عام جديد",
    announcementTitle: "عنوان الإعلان",
    enterAnnouncementTitle: "أدخل عنوان الإعلان",
    announcementContent: "محتوى الإعلان",
    enterAnnouncementContent: "أدخل محتوى الإعلان",
    announcementScope: "نطاق الإعلان",
    selectAnnouncementScope: "اختر نطاق الإعلان",
    singleSemesterProjects: "المشاريع المسجلة في فصل دراسي واحد",
    twoSemestersProjects: "المشاريع الممتدة على فصلين دراسيين",
    other: "أخرى",
    selectTargetCategory: "حدد الفئة المستهدفة من الإعلان",
    pinAnnouncement: "تثبيت الإعلان",
    announcementWillAppearOnTop: "سيظهر الإعلان في أعلى القائمة",
    publishAnnouncement: "نشر الإعلان",
    announcementPublishedSuccessfully: "تم نشر الإعلان بنجاح",
    errorPublishingAnnouncement: "حدث خطأ أثناء نشر الإعلان",
    noAnnouncements: "لا توجد إعلانات",
    noAnnouncementsYet: "لم يتم نشر أي إعلانات بعد. ابدأ بنشر إعلان عام جديد.",
    confirmDeleteAnnouncement: "هل أنت متأكد من حذف هذا الإعلان؟",
    announcementDeletedSuccessfully: "تم حذف الإعلان بنجاح",
    errorDeletingAnnouncement: "حدث خطأ أثناء حذف الإعلان",
    unpin: "إلغاء التثبيت",
    pin: "تثبيت",
    unpinned: "تم إلغاء التثبيت",
    announcementPinned: "تم تثبيت الإعلان",

    // General
    fillAllRequiredFields: "يرجى ملء جميع الحقول المطلوبة",
    required: "مطلوب",

    // Common Actions
    total: "الإجمالي",
    noContent: "لا يوجد محتوى",
    viewAll: "عرض الكل",
    typeMessage: "اكتب رسالتك هنا...",
    attachedFiles: "الملفات المرفقة",
    attachFile: "يجب إرفاق ملف أو كتابة نص",
    feedback: "الملاحظات",

    // Task & Grading
    taskSubmitted: "تم التسليم",
    taskGraded: "تم التقييم",
    grade: "الدرجة",
    weight: "الوزن",
    maxGrade: "الدرجة الكاملة",
    evaluationFeedback: "ملاحظات التقييم",
    noGradesYet: "لا توجد تقييمات بعد",
    errorLoadingTasks: "حدث خطأ في تحميل المهام",
    userNotFound: "المستخدم غير موجود",
    newTaskAssigned: "مهمة جديدة",
    YourOverallGrade: "درجتك الإجمالية",

    // Project & Students
    activeProjects: "المشاريع النشطة",
    projectsCount: "عدد المشاريع",
    noStudentsWithoutSupervisors: "لا يوجد طلاب بدون مشرفين",
    calendar: "التقويم",
    departments: "إدارة الأقسام",
    selectProject: "اختر المشروع",
    chooseProject: "اختيار المشروع",

    // UI Text
    noProjectsAvailable: "لا توجد مشاريع متاحة",

    // Archive
    selectProjectDescription: "اختر المشروع المؤرشف لاسترجاعه",

    // Supervisors
    addSupervisor: "إضافة مشرف",
    addNewSupervisor: "إضافة مشرف جديد",
    enterSupervisorData: "أدخل بيانات المشرف الأكاديمي",
    jobNumber: "الرقم الوظيفي",
    enterJobNumber: "أدخل الرقم الوظيفي",
    supervisorAddedSuccessfully: "تم إضافة المشرف بنجاح",
    errorAddingSupervisorAccount: "حدث خطأ أثناء إضافة المشرف",
    supervisorsAndStudents: "المشرفين والطلاب",
    supervisorsAndStudentsManagement: "إدارة المشرفين الأكاديميين والطلاب",
    noSupervisorsYet: "لا يوجد مشرفين حالياً",
    startByAddingSupervisors: "ابدأ بإضافة مشرفين جدد",
    projectsManagement: "إدارة المشاريع",

    // Notifications, Departments, and Reports
    nothingToShow: "لا يوجد شيء لعرضه",
    departmentsManagement: "إدارة الأقسام",
    addDepartment: "إضافة قسم",
    editDepartment: "تعديل القسم",
    deleteDepartment: "حذف القسم",
    departmentCode: "كود القسم",
    departmentNameAr: "الاسم بالعربي",
    departmentNameEn: "الاسم بالإنجليزي",
    departmentDescription: "وصف القسم",
    departmentActive: "القسم نشط",
    departmentInactive: "القسم معطل",
    noDepartments: "لا توجد أقسام",
    departmentAddedSuccessfully: "تم إضافة القسم بنجاح",
    departmentUpdatedSuccessfully: "تم تحديث القسم بنجاح",
    departmentDeletedSuccessfully: "تم حذف القسم بنجاح",
    errorAddingDepartment: "حدث خطأ أثناء إضافة القسم",
    errorUpdatingDepartment: "حدث خطأ أثناء تحديث القسم",
    errorDeletingDepartment: "حدث خطأ أثناء حذف القسم",
    confirmDeleteDepartment: "هل أنت متأكد من حذف هذا القسم؟",
    addDepartmentDescription: "إضافة وتعديل الأقسام الأكاديمية",
    canStudentsRegister: "يمكن للطلاب التسجيل في هذا القسم",
    reportsAndStatistics: "التقارير والإحصائيات",
    performanceReports: "إحصائيات وتقارير الأداء",
    generateReport: "تحميل التقرير",
    completionRate: "معدل الإنجاز",
    completionRateDescription: "نسبة المشاريع المكتملة من الإجمالي",
    averageProjectsPerSupervisor: "متوسط المشاريع لكل مشرف",
    averageProjectsDescription: "عدد المشاريع المخصصة لكل مشرف",
    completedProjects: "المشاريع المكتملة",
    pendingProjects: "المشاريع المعلقة",
    totalSupervisors: "عدد المشرفين",
    reportDate: "تاريخ التقرير",
    generalStatistics: "إحصائيات عامة",
    reportInformation: "معلومات التقرير",
    additionalProjectDetails: "تفاصيل إضافية حول المشاريع",
    inactive: "معطل",
    enabled: "مفعل",
    disabled: "معطل",

    // Messages Page
    conversations: "المحادثات",
    noConversations: "لا توجد محادثات",
    noMessagesYet: "لا توجد رسائل بعد",
    startConversation: "ابدأ المحادثة بإرسال رسالة",
    selectConversation: "اختر محادثة",
    selectConversationToStart: "اختر محادثة من القائمة لبدء المراسلة",
    writeMessage: "اكتب رسالتك...",
    now: "الآن",

    // Project Page Extra
    browseAvailableIdeas: "تصفح الأفكار المتاحة",
    cannotSubmitNewIdea: "لا يمكنك تقديم فكرة جديدة حالياً لأن لديك فكرة قيد المراجعة أو مقبولة",
    rejectionReasonLabel: "سبب الرفض",

    // Tasks Page Extra
    supervisorFilesForTask: "ملفات المشرف للمهمة",
    submitTask: "تسليم المهمة",
    editSubmission: "تعديل التسليم",
    taskPending: "قيد الانتظار",

    // Coordinator Dashboard
    overviewAllProjects: "نظرة عامة شاملة على جميع المشاريع",
    totalProjectsCount: "إجمالي المشاريع",
    activeProjectsCount: "المشاريع النشطة",
    completedProjectsCount: "المشاريع المكتملة",
    supervisorsCount: "المشرفين",
    studentsCount: "الطلاب",
    averageOverallProgress: "متوسط التقدم العام",
    averageProgressDescription: "نسبة التقدم المتوسطة لجميع المشاريع النشطة",
    activeProjectsLabel: "مشروع نشط",
    needsFollowUp: "يحتاج متابعة",
    successRate: "معدل النجاح",
    successRateDescription: "نسبة المشاريع المكتملة من الإجمالي",
    outOf: "من أصل",
    recentProjectsLabel: "المشاريع الأخيرة",
    recentProjectsDescription: "آخر المشاريع المسجلة في النظام",
    noProjectsCurrently: "لا توجد مشاريع حالياً",
    mostActiveSupervisors: "أكثر المشرفين نشاطاً",
    byProjectsAssigned: "حسب عدد المشاريع المسندة",
    noSupervisorsCurrently: "لا يوجد مشرفين حالياً",

    // Projects Page
    noTitle: "مشروع بدون عنوان",
    noDescription: "لا يوجد وصف",
    awaitingApproval: "بانتظار الموافقة",
    stopped: "موقوف",
    unknown: "غير معروف",
    progressLabel: "التقدم",
    startDateLabel: "تاريخ البدء:",
    endDateLabel: "تاريخ الانتهاء:",
    supervisorLabel: "المشرف:",
    departmentLabel: "القسم:",
    studentLabel: "الطالب:",
    fillRequiredFields: "يرجى ملء جميع الحقول المطلوبة",
    errorLoadingProjectsMsg: "حدث خطأ في تحميل المشاريع",
    projectAcceptedSuccess: "تم قبول المشروع بنجاح",
    projectRejectedMsg: "تم رفض المشروع",
    projectStoppedMsg: "تم إيقاف المشروع مؤقتاً",
    projectArchivedMsg: "تم أرشفة المشروع",
    errorAcceptingProject: "حدث خطأ في قبول المشروع",
    errorRejectingProjectMsg: "حدث خطأ في رفض المشروع",
    errorStoppingProject: "حدث خطأ في تعليق المشروع",
    errorArchivingProjectMsg: "حدث خطأ في أرشفة المشروع",
    projectAddedSuccess: "تم إضافة المشروع بنجاح",
    projectUpdatedSuccess: "تم تحديث المشروع بنجاح",
    projectDeletedMsg: "تم حذف المشروع",
    errorAddingProjectMsg: "حدث خطأ أثناء إضافة المشروع",
    errorUpdatingProjectMsg: "حدث خطأ أثناء تحديث المشروع",
    errorDeletingProjectMsg: "حدث خطأ في حذف المشروع",
    studentAddedToProjectSuccess: "تم إضافة الطالب إلى المشروع بنجاح",
    studentRemovedFromProject: "تم حذف الطالب من المشروع",
    studentAlreadyHasProjectMsg: "هذا الطالب لديه مشروع بالفعل",
    errorAddingStudentMsg: "حدث خطأ أثناء إضافة الطالب",
    errorRemovingStudentMsg: "حدث خطأ أثناء حذف الطالب",
    errorLoadingTeamMembersMsg: "حدث خطأ في تحميل أعضاء الفريق",
    pleaseSelectStudentMsg: "يرجى اختيار طالب",
    ideaDataLoadedMsg: "تم تحميل بيانات الفكرة المقبولة، يرجى اختيار المشرف",
    errorLoadingIdeaDataMsg: "حدث خطأ في تحميل بيانات الفكرة",

    // Supervisors Page
    addSupervisorBtn: "إضافة مشرف",
    addStudentBtn: "إضافة طالب",
    addNewSupervisorTitle: "إضافة مشرف جديد",
    enterSupervisorDataDesc: "أدخل بيانات المشرف الأكاديمي",
    addNewStudentTitle: "إضافة طالب جديد",
    enterStudentDataDesc: "أدخل بيانات الطالب",
    fullNameLabel: "الاسم الكامل",
    jobNumberLabel: "الرقم الوظيفي",
    phoneNumberLabel: "رقم الهاتف",
    passwordLabel: "كلمة المرور",
    enterPasswordPlaceholder: "أدخل كلمة المرور",
    emailLabel: "البريد الإلكتروني",
    departmentSelectLabel: "القسم",
    selectDepartmentPlaceholder: "اختر القسم",
    loadingText: "جاري التحميل...",
    cancelBtn: "إلغاء",
    addBtn: "إضافة",
    supervisorAddedSuccess: "تم إضافة المشرف بنجاح",
    emailAlreadyInUseMsg: "البريد الإلكتروني مستخدم بالفعل",
    errorAddingSupervisorMsg: "حدث خطأ أثناء إضافة المشرف",
    studentAddedSuccess: "تم إضافة الطالب بنجاح",
    errorAddingStudentAccountMsg: "حدث خطأ أثناء إضافة الطالب",
    noSupervisorsYetMsg: "لا يوجد مشرفين حالياً",
    startAddingSupervisors: "ابدأ بإضافة مشرفين جدد",
    projectsCountLabel: "عدد المشاريع",
    projectWord: "مشروع",
    noStudentsYetMsg: "لا يوجد طلاب حالياً",
    studentsWillAppear: "سيظهر الطلاب هنا بعد التسجيل",
    universityIdLabel: "الرقم الجامعي",

    // Students Page
    studentsManagementTitle: "إدارة الطلاب",
    assignSupervisorsDesc: "تعيين المشرفين للطلاب ومتابعة حالتهم",
    addNewStudentBtn: "إضافة طالب جديد",
    totalStudentsLabel: "إجمالي الطلاب",
    studentsWithoutSupervisorLabel: "طلاب بدون مشرف",
    studentsWithSupervisorLabel: "طلاب مع مشرف",
    studentsListTitle: "قائمة الطلاب",
    studentsListDesc: "جميع الطلاب المسجلين في النظام",
    assignedStatus: "تم التعيين",
    withoutSupervisorStatus: "بدون مشرف",
    changeSupervisorBtn: "تغيير المشرف",
    assignSupervisorBtn: "تعيين مشرف",
    assignSupervisorTitle: "تعيين مشرف",
    selectSupervisorForStudent: "اختر المشرف المناسب للطالب",
    supervisorSelectLabel: "المشرف",
    selectSupervisorPlaceholder: "اختر المشرف",
    studentWord: "طالب",
    selectedSupervisorLabel: "المشرف المختار:",
    currentStudentsCountLabel: "عدد الطلاب الحالي:",
    assignBtn: "تعيين",
    supervisorAssignedSuccess: "تم تعيين المشرف بنجاح",
    errorAssigningSupervisorMsg: "حدث خطأ أثناء تعيين المشرف",
    selectSupervisorMsg: "يرجى اختيار مشرف",
    confirmChangeSupervisor: "تأكيد تغيير المشرف",
    studentLinkedToProject: "هذا الطالب مرتبط مسبقاً بمشروع أو مشرف.",
    studentName: "الطالب:",
    currentSupervisorLabel: "المشرف الحالي:",
    newSupervisorLabel: "المشرف الجديد:",
    teamUpdateWarning: "تنبيه: الطالب لديه مشروع مرتبط. عند التأكيد سيتم تغيير مشرف المشروع وتحديث كل أعضاء الفريق.",
    confirmChangeQuestion: "هل أنت متأكد من تغيير المشرف؟",
    confirmBtn: "تأكيد التغيير",
    notSpecifiedText: "غير محدد",
    noSupervisorText: "لا يوجد",
    errorLoadingDataMsg: "حدث خطأ أثناء تحميل البيانات",

    // Pending Invites
    pendingInvite: "دعوة معلقة",
    pendingInvites: "دعوات معلقة",
    teamApprovalPending: "لديك طلبات انضمام لفريق بانتظار موافقتك",

    // Total Grade
    totalGrade: "الدرجة الإجمالية",

    //team approval page
    reviewPendingInvites: "قم بمراجعة والموافقة على دعوات الانضمام للمشاريع الجماعية",
    noPendingInvites: "لا توجد دعوات معلقة حالياً",
    approveInvite: "قبول الدعوة",
    rejectInvite: "رفض الدعوة",
    teamInvites: "دعوات المشاريع الجماعية",
    errorLoadingInvites: "حدث خطأ في تحميل الدعوات",
    inviteApproved: "تمت الموافقة على الانضمام للمشروع",
    inviteRejected: "تم رفض الدعوة",
    errorApproving: "حدث خطأ أثناء الموافقة",
    errorRejecting: "حدث خطأ أثناء الرفض",
    browseProjectIdeas: "تصفح أفكار المشاريع المتاحة",

    //calendar psage
    calendarSubtitle: "جميع المهام والاجتماعات في مكان واحد",
    upcomingEvents: "الأحداث القادمة",
    noUpcomingEvents: "لا توجد أحداث قادمة",
    noEventsForSelectedDate: "لا توجد أحداث في هذا اليوم",
    events: "أحداث",
    colorLegend: "دليل الألوان",
    submitted: "مسلم",
    graded: "مقيم",
  
    //monthes & days
      january: "يناير",
      february: "فبراير",
      march: "مارس",
      april: "أبريل",
      may: "مايو",
      june: "يونيو",
      july: "يوليو",
      august: "أغسطس",
      september: "سبتمبر",
      october: "أكتوبر",
      november: "نوفمبر",
      december: "ديسمبر",
      sunday: "الأحد",
      monday: "الاثنين",
      tuesday: "الثلاثاء",
      wednesday: "الأربعاء",
      thursday: "الخميس",
      friday: "الجمعة",
      saturday: "السبت",

      //messages page
      searchPlaceholder: "بحث...",
      selectConversationInstructions: "اختر محادثة من القائمة لبدء المراسلة",
      writeYourMessage: "اكتب رسالتك...",
      userFallbackName:"مستخدم",
      noMessagesYetText:"لا توجد رسائل بعد. ابدأ المحادثة بإرسال رسالة.",
      errorSendingMessageMsg:"حدث خطأ أثناء إرسال الرسالة",

      //project idea page
      youHaveActiveProjectIdea:"لديك فكرة مشروع قيد المراجعة أو تمت الموافقة عليها",
      errorCheckingSubmissionEligibility:"حدث خطأ أثناء التحقق من إمكانية التقديم",
      errorLoadingDepartments:"حدث خطأ أثناء تحميل الأقسام",
      shouldBeAtLeastTwoStudents:"يجب أن يكون هناك طالبين على الأقل في المشروع",
      gpaMustNotExceed4:"المعدل التراكمي يجب أن لا يزيد عن 4.00",
      pleaseSelectProjectDepartment:"يرجى اختيار قسم المشروع",
      departmentNotValid:"قسم المشروع غير صحيح",
      pleaseCompleteStudentInfo:"يرجى إكمال معلومات جميع الطلاب",
      pleaseSelectStudentDepartment:"يرجى اختيار قسم الطالب",
      pleaseAcceptPlagiarismDeclaration:"يجب الموافقة على إقرار الأصالة",
      studentAlreadyInAnotherProject:" لا يمكن تقديم الفكرة: الطالب ",
      alreadyInAnotherProject:" موجود بالفعل في مشروع آخر قيد المراجعة أو تمت الموافقة عليه",
      haveActiveProject:" لديه مشروع نشط بالفعل",
      newProjectIdea:"فكرة مشروع جديدة",
      studentSubmittedNewProjectIdea:"قدم الطالب ",
      projectTeamInvitation:"دعوة للانضمام إلى مشروع",
      youHaveBeenInvitedToJoinProject:"تمت دعوتك للانضمام إلى مشروع",
      by: "بواسطة ",
      pleaseReviewAndAcceptTheInvitation: "يرجى مراجعة وقبول الدعوة للانضمام إلى فريق المشروع.",
      projectIdeaSubmittedSuccessfully:"تم تقديم فكرة المشروع بنجاح! تم إرسال دعوات لأعضاء الفريق.",
      errorSubmittingProjectIdea:"حدث خطأ أثناء تقديم فكرة المشروع",
      checkingProjectStatus:"جاري التحقق...",
      submitYourGraduationProjectIdea:"قدم فكرة مشروع التخرج الخاص بك",
      youCannotSubmitNewIdeaCurrently:"لا يمكنك تقديم فكرة جديدة حالياً. لديك فكرة قيد المراجعة أو تمت الموافقة عليها.",
      Note:"ملاحظة:",
      afterSubmittingProjectIdea:"جميع المشاريع يجب أن تكون جماعية (طالبين على الأقل). بعد المراجعة، يجب على جميع الأعضاء الموافقة على الفكرة والمشاركة.",
      basicInformation:"المعلومات الأساسية",
      basicInformationDescription:"معلومات عامة عن المشروع والبرنامج",
      program: "البرنامج",
      egComputerScience:"مثال: بكالوريوس علوم الحاسب",
      academicYear: "السنة الأكاديمية",
      egAcademicYear:"مثال: 2024-2025",
      semester: "الفصل الدراسي",
      selectSemester:"اختر الفصل الدراسي",
      firstSemester: "الفصل الأول",
      secondSemester: "الفصل الثاني",
      selectProjectType:"اختر نوع المشروع",
      oneCourse: "مشروع فصل دراسي واحد",
      twoCourses: "مشروع فصلين دراسيين",
      studentsInformation:"معلومات الطلاب",
      studentsInformationDescription:"معلومات جميع أعضاء الفريق (2 على الأقل)",
      gpa:"المعدل التراكمي",
      supervisorInformation:"معلومات المشرف",
      supervisorDescription:"بيانات المشرف الرئيسي والمشرف المساعد (إن وجد)",
      supervisorName:"اسم المشرف",
      supervisorEmail:"البريد الإلكتروني للمشرف (UoB)",
      coSupervisorName:"اسم المشرف المساعد (إن وجد)",
      coSupervisorEmail:"البريد الإلكتروني للمشرف المساعد",
      projectDetailsDescription:"وصف شامل للمشروع وأهدافه",
      problemStatement:"بيان المشكلة",
      significance:"أهمية المشروع",
      literatureReview:"مراجعة الأدبيات الموجزة",
      references:"المراجع الداعمة",
      projectTimeline:"الجدول الزمني للمشروع",
      projectTimelineDescription:"مخطط زمني مقترح للمشروع",
      plagiarismDeclaration:"إقرار الأصالة",
      plagiarismDeclarationDescription:"يجب الموافقة على الإقرار لتقديم المشروع",
      plagiarismDeclarationLabel:"أقر بأن هذا العمل من إعدادي الخاص وأن جميع المراجع والمصادر المستخدمة قدتم الإشارة إليها بشكل صحيح. ",
      submitting:"جاري التقديم...",
      submitIdea:"تقديم الفكرة",
      requirementCollection: "جمع المتطلبات",
      design: "التصميم",
      implementation: "التنفيذ",
      testingAndResults: "الاختبار والنتائج",
      reportWriting: "كتابة التقرير",
      presentation: "العرض التقديمي",
      phase: "المرحلة",

      //ideas page
      errorLodingProjectIdeas:"حدث خطأ أثناء تحميل أفكار المشاريع",
      notFoundIdea:"فكرة المشروع غير موجودة",
      errorLoadingIdeasInfo:"حدث خطأ أثناء تحميل تفاصيل الفكرة",
      ideaSelectedByMe:"تم اختيار هذه الفكرة من قبلك",
      ideaTakenByOtherStudent:"تم اختيار هذه الفكرة من قبل طالب آخر",
      youCannotPickAnotherIdea:"لا يمكنك اختيار أكثر من فكرة. لديك فكرة مختارة بالفعل.",
      ideaSelectedSuccessfully:"تم اختيار الفكرة بنجاح!",
      userNotFoundInDatabase:"حسابك غير موجود في قاعدة البيانات",
      errorSelectingIdea:"حدث خطأ أثناء اختيار الفكرة",
      available: "متاحة",
      takenByOtherStudent: "مأخوذة",
      selected: "مختارة",
      noIdeaSelected: "لم يتم اختيار أي فكرة بعد",
      browseAndSelectProjectIdeasDescription:" تصفح واختر من أفكار المشاريع المطروحة من المشرفين (فكرة واحدة فقط)",
      mySelectedIdea:"فكرتي المختارة",
      mySelectedIdeaDescription:"تظهر هنا الفكرة التي اخترتها (إن وجدت)",
      noIdeaSelectedYet:"لم تقم باختيار أي فكرة بعد. تصفح الأفكار المتاحة واختر واحدة لتبدأ مشروعك.",
      availableIdeas:"الأفكار المتاحة",
      availableIdeasDescription:"فكرة متاحة للإختبار",
      noAvailableIdeasCurrently:"لا توجد أفكار متاحة حالياً",
      noAvailableIdeasDescription:"لم يتم طرح أي أفكار متاحة من المشرفين بعد",
      ideaDetails:"تفاصيل فكرة المشروع المقترحة",
      technologiesUsed:"التقنيات المستخدمة",
      projectOption:"خيار المشروع",
      selecting: "جاري الاختيار...",
      youHaveAlreadySelectedAnIdea:"لديك فكرة مختارة بالفعل",
      ideaNotAvailable:"تم أخذ الفكرة",
      selectThisIdea:"اختيار هذه الفكرة",

      //coordinate project page
      TemporarySuspension:"إيقاف مؤقت",
      activateProject:"تفعيل ",
      addNewProject:"إضافة مشروع جديد",
      enterProjectDetailsAndAssignSupervisorAndStudent:"أدخل بيانات المشروع وقم بتعيين المشرف والطالب",
      enterProjectTitle:"أدخل عنوان المشروع",
      enterProjectDescription:"أدخل وصف المشروع",
      projectStartDate:"تاريخ بدء المشروع",
      projectEndDate:"تاريخ انتهاء المشروع (اختياري)",
      selectSupervisor:"اختر المشرف",
      stu:"الطالب (اختياري)",
      selectStudent:"اختر الطالب",
      noStudent:"بدون طالب",
      addProj:"إضافة المشروع",
      searchProjects:"ابحث في المشاريع...",
      noMatchingResults:"لا توجد نتائج مطابقة",
      startAddingProjects:"ابدأ بإضافة مشاريع جديدة",

      //coordinate supervisor page
      pleaseFillAllRequiredFields:"يرجى ملء جميع الحقول المطلوبة",
      errorAddingSupervisor:"حدث خطأ أثناء إضافة المشرف",
      studentAdded:"تم إضافة الطالب بنجاح",
      manageSupervisorsAndStudents:"إدارة المشرفين الأكاديميين والطلاب",
      enterSupervisorDetails:"أدخل بيانات المشرف الأكاديمي",
      egDrAhmedMohamed:"د. أحمد محمد",
      supervisorId:"الرقم الوظيفي",
      egEMP12345:"مثال: EMP12345",
      enterSupervisorId:"أدخل الرقم الوظيفي",
      chooseDepartment:"اختر القسم",
      enterStudentDetails:"أدخل بيانات الطالب",
      egAhmedMohamed:"أحمد محمد",
      addNewSupervisors:"ابدأ بإضافة مشرفين جدد",
      numberOfProjects:"عدد المشاريع",
      addNewStudents:"ابدأ بإضافة طلاب جدد",

      //coordinate students page
      None: "لايوجد",
      manageStudents:"إدارة الطلاب",
      assignSupervisorsAndTrackStudents:"تعيين المشرفين للطلاب ومتابعة حالتهم",
      studentsWillAppearAfterRegistration:"سيظهر الطلاب هنا بعد التسجيل",
      allStudentsInSystem:"جميع الطلاب المسجلين في النظام",
      noSupervisor:"لا يوجد مشرف",
      studentAlreadyAssignedToProjectOrSupervisor:"هذا الطالب مرتبط مسبقاً بمشروع أو مشرف.",
      alertStudentHasProjectLinked:"تنبيه: الطالب لديه مشروع مرتبط. عند التأكيد سيتم تغيير مشرف المشروع وتحديث كل أعضاء الفريق.",
      AreYouSureYouWantToChangeTheSupervisor:"هل أنت متأكد من تغيير المشرف؟",
      YesChange: "نعم، غيّر",
      addNewStudentDescription:"أدخل بيانات الطالب لإنشاء حساب جديد",
      enterStudentId:"مثال: 202012345",
      addDepartmentsFromManagementPage:"يرجى إضافة أقسام من صفحة إدارة الأقسام",
      enterPhone:"مثال: 39335681",

      //coordinate departments page
      errorSavingDepartment:"حدث خطأ أثناء حفظ القسم",
      manageDepartments:"إدارة الأقسام",
      AddAndEditAcademicDepartments:"إضافة وتعديل الأقسام الأكاديمية",
      addNewDepartmentInstructions:"ابدأ بإضافة قسم أكاديمي جديد",
      addNewDepartment:"إضافة قسم جديد",
      updateDepartmentInfo:"قم بتحديث معلومات القسم",
      enterNewDepartmentInfo:"أدخل معلومات القسم الجديدة",
      departmentCodeLabel:"كود القسم",
      egCS:"مثال: cs, it, is",
      egDepartmentName:"مثال: علوم الحاسب",
      egDepartmentNameEn:"مثال: Computer Science",
      departmentDescriptionPlaceholder:"وصف مختصر للقسم",
      isActiveDepartment:"القسم نشط",
      departmentCanBeSelectedByStudents:"يمكن للطلاب التسجيل في هذا القسم",
      theCode: "الكود",
      
      //coordinate messages page
      user: "مستخدم",
      NoMessagesYet: "لا توجد رسائل بعد",
      errorLoadingConversations:"حدث خطأ أثناء تحميل المحادثات",
      errorSendingMessage:"حدث خطأ أثناء إرسال الرسالة",
      searchByName:"بحث بالاسم...",
      NoMessages:"لا توجد رسائل",
      message: "رسالة",
      forSending: "للإرسال",
      forNewLine: "لسطر جديد",
      chooseConversation:"اختر محادثة",
      chooseConversationDescription:"اختر محادثة من القائمة لبدء المراسلة",
      messagesm:"المحادثات",

      //coordinate announcements page
      announcementPinnedSuccessfully:"تم تثبيت الإعلان",
      announcementUnpinnedSuccessfully:"تم إلغاء التثبيت",
      AnErrorOccurred: "حدث خطأ",
      singleSemesterProject:"مشاريع فصل واحد",
      twoSemesterProjects:"مشاريع فصلين دراسيين",
      manageAndPublishGeneralAnnouncements:"إدارة ونشر الإعلانات العامة لجميع المستخدمين",
      publishNewGeneralAnnouncement:"نشر إعلان عام جديد",
      selectAnnouncementScopeDescription:"حدد الفئة المستهدفة من الإعلان",
      announcementWillBePinnedToTopOfList:"سيظهر الإعلان في أعلى القائمة",
      noAnnouncementsDescription:"لم يتم نشر أي إعلانات بعد. ابدأ بنشر إعلان عام جديد.",

      //cordinate reports page
      graduationProjectsReport:"تقرير-مشاريع-التخرج-",
      reportsDescription:"إحصائيات وتقارير الأداء",
      downloadReport: "تحميل التقرير",
      totalProjects: "إجمالي المشاريع",
      supervisorsNumber: "عدد المشرفين",
      studentsNumber: "عدد الطلاب",
      reportDetails: "تفاصيل التقرير",
      reportDetailsDescription: "تفاصيل إضافية حول المشاريع",
      projectsPerSupervisor: "متوسط المشاريع لكل مشرف",
      projectsPerSupervisorDescription: "عدد المشاريع المخصصة لكل مشرف",
      graduationProjectsReportTitle: "تقرير مشاريع التخرج",

      //cordinate solo exceptions page
      errorLoadingStudents:"حدث خطأ في تحميل قائمة الطلاب",
      studentExceptionRemoved:"تم إلغاء الاستثناء من الطالب بنجاح",
      studentExceptionGranted:"تم منح الاستثناء للطالب بنجاح",
      errorUpdatingException:"حدث خطأ أثناء تحديث الاستثناء",
      soloProjectExceptions:"استثناءات المشاريع الفردية",
      manageStudentsWithSoloProjectExceptions:"إدارة الطلاب المصرح لهم بتقديم مشاريع فردية",
      studentsWithSoloProjectExceptions:"لديهم استثناء",

      //Id Page
      errorLoadingDiscussion:"حدث خطأ أثناء تحميل النقاش",
      thisDiscussionIsClosedCannotReply:"هذا النقاش مغلق ولا يمكن الرد عليه",
      addedReplySuccessfully:"تم إضافة الرد بنجاح",
      errorAddDiscussion:"حدث خطأ أثناء إضافة الرد",
      anErrorOccurred:"حدث خطأ",
      replyNotFound:"الرد غير موجود",
      discussionDetails:"تفاصيل النقاش",

      //file upload page
      pleaseChoosePicOnly:"يرجى اختيار ملفات صور فقط (JPG, PNG, GIF, etc.)",
      unknowError:"خطأ غير معروف",
    },

  en: {
    // Common
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    submit: "Submit",
    search: "Search",
    filter: "Filter",
    close: "Close",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    actions: "Actions",
    view: "View",
    download: "Download",
    upload: "Upload",
    send: "Send",
    back: "Back",
    next: "Next",
    previous: "Previous",
    select: "Select",
    selectAll: "Select All",
    clear: "Clear",
    reset: "Reset",
    apply: "Apply",
    create: "Create",
    update: "Update",
    remove: "Remove",

    // Roles
    student: "Student",
    supervisor: "Supervisor",
    coordinator: "Coordinator",
    admin: "Admin",

    // Sidebar Navigation
    dashboard: "Dashboard",
    myProject: "My Project",
    tasks: "Tasks",
    meetings: "Meetings",
    files: "Files",
    announcements: "Announcements",
    discussions: "Discussions",
    messages: "Messages",
    grades: "Grades",
    notifications: "Notifications",
    settings: "Settings",
    logout: "Logout",
    profile: "Profile",
    projects: "Projects",
    students: "Students",
    supervisors: "Supervisors",
    reports: "Reports",
    archive: "Archive",
    assignSupervisors: "Assign Supervisors",
    projectIdeas: "Project Ideas",
    evaluations: "Evaluations",
    tasksAndEvaluation: "Tasks and Evaluation",

    // Platform
    platformTitle: "Projects Platform",
    graduationProjectsPlatform: "Graduation Projects Platform",
    mainMenu: "Main Menu",
    mainNavDescription: "Main navigation menu to access all system sections",

    // Auth Pages
    login: "Login",
    register: "Register",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    name: "Name",
    phone: "Phone",
    studentId: "Student ID",
    employeeId: "Employee ID",
    department: "Department",
    role: "Role",
    loginButton: "Login",
    loggingIn: "Logging in...",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    invalidCredentials: "Invalid email or password",

    // Dashboard
    welcome: "Welcome",
    welcomeBack: "Welcome back",
    overviewText: "Here's an overview of your graduation project",
    supervisorOverview: "Overview of projects you supervise",
    coordinatorOverview: "Overview of all projects",
    totalTasks: "Total Tasks",
    completedTasks: "Completed Tasks",
    upcomingMeetings: "Upcoming Meetings",
    projectProgress: "Project Progress",
    recentTasks: "Recent Tasks",
    recentNotifications: "Recent Notifications",
    latestUpdates: "Latest Updates",
    noTasksYet: "No tasks yet",
    noDataFound: "User data not found",
    errorLoadingData: "Error loading data",
    errorOccurred: "An error occurred",
    welcomeToplatform: "Welcome to the Platform",
    startByAddingProject: "Start by adding your project and tracking tasks",

    // Project Page
    projectDetails: "Your graduation project details",
    myProjectDetails: "My Project Details",
    submitProjectIdea: "Submit Project Idea",
    submittedProjectIdeas: "Submitted Project Ideas",
    projectIdeasStatus: "Status of your submitted project ideas",
    submissionDate: "Submission Date",
    approved: "Approved",
    rejected: "Rejected",
    underReview: "Under Review",
    noProjectAssigned: "No project assigned yet",
    projectSubmittedUnderReview:"Project idea has been submitted and is under review. You will be notified of the decision soon.",
    submitOrWait: "Submit a project idea or wait for project assignment from the academic coordinator",
    active: "Active",
    completed: "Completed",
    pending: "Pending",
    inProgress: "In Progress",
    startDate: "Start Date",
    endDate: "End Date",
    expectedDeliveryDate: "Expected Delivery Date",
    notSpecified: "Not Specified",
    tasksAndAssignments: "Tasks and Assignments",
    discussionForum: "Discussion Forum",
    evaluationsAndResults: "Evaluations and Results",
    supervisorInfo: "Project supervisor information",
    contactSupervisor: "Contact Supervisor",
    projectObjectives: "Project Objectives",
    noObjectivesYet: "No objectives set yet",
    projectTitle: "Project Title",
    projectDescription: "Project Description",
    projectStatus: "Project Status",
    projectType: "Project Type",
    ideasWaitingDecision: "Submitted project ideas awaiting a decision",
    approvedPlural: "Approved",
    ideasApproved: "Approved project ideas",
    rejectedPlural: "Rejected",
    ideasRejected: "Rejected project ideas",
    noIdeasUnderReview: "There are currently no project ideas under review",
    allIdeasReviewed: "All submitted project ideas have been reviewed",
    noApprovedIdeas: "There are currently no approved project ideas",
    noIdeaApprovedYet: "No project idea has been approved yet",
    noRejectedIdeas: "There are currently no rejected project ideas",
    noIdeaRejectedYet: "No project idea has been rejected yet",
    projectIdeaDetailsDesc: "Details of the project idea submitted by the student",
    description: "Description",
    notAssignedYet: "Not assigned yet",
    approveIdea: "Approve Idea",
    rejectIdea: "Reject Idea",
    approveAssignSupervisorsTitle: "Approve Project Idea and Assign Supervisors",
    teamProject: "Team Project",
    chooseSupervisorsAndDatesDesc: "Choose the appropriate supervisors and set the project start and end dates",
    leader: "Leader",
    supervisorsRequiredMulti: "Supervisors are required for team projects",
    primarySupervisor: "Primary Supervisor",
    secondarySupervisor: "Secondary Supervisor",
    endDateOptional: "End Date (Optional)",
    approving: "Approving...",
    approveAndCreateProject: "Approve and Create Project",
    rejectProjectIdeaTitle: "Reject Project Idea",
    pleaseExplainRejectionReason: "Please explain the reason for rejecting the project idea",
    project: "Project",
    rejectionReason: "Rejection Reason",
    writeRejectionReasonPlaceholder: "Write the reason for rejection here...",
    confirmReject: "Are you sure you want to reject this idea?",
    formProjectTeamTitle: "Form Project Team",
    formTeamDesc: "Select the students who will form this project team",
    currentTeamMembers: "Current Team Members",
    default: "Default",
    secondary: "Secondary",
    addStudentToTeam: "Add Student to Team",
    selectStudentt: "Select a Student",
    noAvailableStudents: "No available students to join the team",


    // Tasks
    taskTitle: "Task Title",
    taskDescription: "Task Description",
    taskStatus: "Task Status",
    taskPriority: "Task Priority",
    dueDate: "Due Date",
    assignedTo: "Assigned To",
    assignedBy: "Assigned By",
    new: "New",
    high: "High",
    medium: "Medium",
    low: "Low",
    urgent: "Urgent",
    addTask: "Add Task",
    editTask: "Edit Task",
    deleteTask: "Delete Task",
    completeTask: "Complete Task",
    markAsComplete: "Mark as Complete",
    markAsIncomplete: "Mark as Incomplete",
    approveRejectProjectIdeasTitle: "Approve or Reject Project Ideas",
    approveRejectProjectIdeasDesc: "Review submitted project ideas and approve or reject them",

    // Meetings
    meetingTitle: "Meeting Title",
    meetingDescription: "Meeting Description",
    meetingDate: "Meeting Date",
    meetingTime: "Meeting Time",
    meetingLocation: "Meeting Location",
    meetingLink: "Meeting Link",
    meetingStatus: "Meeting Status",
    scheduled: "Scheduled",
    canceled: "Canceled",
    addMeeting: "Add Meeting",
    editMeeting: "Edit Meeting",
    deleteMeeting: "Delete Meeting",
    joinMeeting: "Join Meeting",
    scheduleMeeting: "Schedule Meeting",
    noMeetingsYet: "No meetings yet",
    upcomingMeeting: "Upcoming Meeting",
    pastMeeting: "Past Meeting",
    requestMeeting: "Request Meeting",
    meetingNotes: "Meeting Notes",
    date: "Date",
    time: "Time",
    meetingRequests: "Meeting Requests",
    submittedOn: "Submitted on",
      teamStatus: "Team Status",
      ideaSubmittedBy: "Idea Submitted By",
      submittedAt: "Submitted At",
      waitingTeamFormation: "Waiting for team formation",
      notApprovedYet: "Not approved yet",
      waitingSomeMembersApproval: "Waiting for some members to approve",
      teamNotFormed: "Team not formed",
    timeRange: "From 8 AM to 8 PM",
    meetingsBetweenHours: "Meetings must be between 8 AM and 8 PM",
    fieldRequired: "Please fill all required fields",
    savedSuccessfully: "Saved successfully",
    errorMessage: "An error occurred, please try again",

    // Archive
    restoreProject: "Restore Project",
    archived: "Archived",
    archivedProjects: "Archived Projects",
    noArchivedProjects: "No archived projects",
    archivedProjectsDescription: "Archived projects will appear here",
    projectRestoredSuccessfully: "Project restored successfully",
    errorRestoringProject: "Error restoring project",

    // Projects
    allProjects: "All Projects",
    approveProjects: "Approve Projects",
    addProject: "Add Project",
    editProject: "Edit Project",
    deleteProject: "Delete Project",
    viewDetails: "View Details",
    projectProposalDetails: "Project Proposal Details",
    acceptProject: "Accept Project",
    rejectProject: "Reject Project",
    suspendProject: "Suspend Project",
    archiveProject: "Archive Project",
    projectApprovedSuccessfully: "Project approved successfully",
    projectRejected: "Project rejected",
    projectSuspended: "Project suspended",
    projectArchived: "Project archived",
    errorApprovingProject: "Error approving project",
    errorRejectingProject: "Error rejecting project",
    errorSuspendingProject: "Error suspending project",
    errorArchivingProject: "Error archiving project",
    projectAddedSuccessfully: "Project added successfully",
    projectUpdatedSuccessfully: "Project updated successfully",
    projectDeletedSuccessfully: "Project deleted",
    errorAddingProject: "Error adding project",
    errorUpdatingProject: "Error updating project",
    errorDeletingProject: "Error deleting project",
    errorLoadingProjects: "Error loading projects",
    suspended: "Suspended",
    progress: "Progress",
    notAssigned: "Not Assigned",
    objectives: "Objectives",
    confirmDelete: "Are you sure you want to delete this project?",
    teamManagement: "Team Management",
    teamMembers: "Team Members",
    addStudentToProject: "Add Student to Project",
    removeStudent: "Remove Student",
    studentAddedSuccessfully: "Student added to project successfully",
    studentRemovedSuccessfully: "Student removed from project",
    studentAlreadyHasProject: "This student already has a project",
    errorAddingStudent: "Error adding student",
    errorRemovingStudent: "Error removing student",
    errorLoadingTeamMembers: "Error loading team members",
    pleaseSelectStudent: "Please select a student",
    ideaDataLoaded: "Approved idea data loaded, please select a supervisor",
    errorLoadingIdeaData: "Error loading idea data",

    // Students
    studentsManagement: "Students Management",
    assignSupervisorsDescription: "Assign supervisors to students and track their status",
    addNewStudent: "Add New Student",
    totalStudents: "Total Students",
    studentsWithoutSupervisor: "Students Without Supervisor",
    studentsWithSupervisor: "Students With Supervisor",
    noStudentsYet: "No students yet",
    studentsWillAppearHere: "Students will appear here after registration",
    studentsList: "Students List",
    allRegisteredStudents: "All registered students in the system",
    assigned: "Assigned",
    withoutSupervisor: "Without Supervisor",
    changeSupervisor: "Change Supervisor",
    assignSupervisor: "Assign Supervisor",
    selectAppropiateSupervisor: "Select the appropriate supervisor for the student",
    selectedSupervisor: "Selected Supervisor",
    currentStudentCount: "Current Student Count",
    supervisorAssignedSuccessfully: "Supervisor assigned successfully",
    errorAssigningSupervisor: "Error assigning supervisor",
    pleaseSelectSupervisor: "Please select a supervisor",
    fullName: "Full Name",
    enterFullName: "Enter full name",
    enterEmail: "Enter email",
    enterPassword: "Enter password",
    universityId: "University ID",
    example: "Example",
    selectDepartment: "Select Department",
    noDepartmentsAvailable: "No departments available",
    addDepartmentsFromSettings: "Please add departments from the departments management page",
    selectedDepartment: "Selected Department",
    phoneNumber: "Phone Number",
    emailAlreadyInUse: "Email already in use",
    errorAddingStudentAccount: "Error adding student",
    assign: "Assign",
    addStudent: "Add Student",
    enterStudentData: "Enter student data to create a new account",

    // Discussions
    shareIdeasWithTeam: "Share ideas and questions with your team",
    newDiscussion: "New Discussion",
    createNewDiscussion: "Create New Discussion",
    discussionTitle: "Discussion Title",
    enterDiscussionTitle: "Enter discussion title",
    discussionContent: "Discussion Content",
    explainDiscussionInDetail: "Explain the discussion topic in detail",
    tags: "Tags",
    optional: "Optional",
    tagsExample: "Example: technical, report, review (separate with comma)",
    separateTagsWithComma: "Separate tags with comma",
    createDiscussion: "Create Discussion",
    discussionCreatedSuccessfully: "Discussion created successfully",
    errorCreatingDiscussion: "Error creating discussion",
    errorFetchingDiscussions: "Error fetching discussions",
    all: "All",
    open: "Open",
    closed: "Closed",
    noDiscussions: "No Discussions",
    noDiscussionsYet: "No discussions created yet. Start by creating a new discussion.",
    pinned: "Pinned",
    reply: "Reply",
    discussionNotFound: "Discussion not found",
    noProject: "No Project",
    mustBeInProjectForDiscussions: "You must be enrolled in a project to participate in discussions",
    mustBeInProjectToCreateDiscussion: "You must have a project to create a discussion",
    fewMinutesAgo: "A few minutes ago",
    hoursAgo: "{hours} hours ago",
    oneDayAgo: "One day ago",

    // Announcements
    announcementsManagement: "Manage and publish general announcements for all users",
    newAnnouncement: "New Announcement",
    publishNewAnnouncement: "Publish New General Announcement",
    announcementTitle: "Announcement Title",
    enterAnnouncementTitle: "Enter announcement title",
    announcementContent: "Announcement Content",
    enterAnnouncementContent: "Enter announcement content",
    announcementScope: "Announcement Scope",
    selectAnnouncementScope: "Select announcement scope",
    singleSemesterProjects: "Single Semester Projects",
    twoSemestersProjects: "Two Semesters Projects",
    other: "Other",
    selectTargetCategory: "Select the target category for the announcement",
    pinAnnouncement: "Pin Announcement",
    announcementWillAppearOnTop: "The announcement will appear at the top of the list",
    publishAnnouncement: "Publish Announcement",
    announcementPublishedSuccessfully: "Announcement published successfully",
    errorPublishingAnnouncement: "Error publishing announcement",
    noAnnouncements: "No Announcements",
    noAnnouncementsYet: "No announcements published yet. Start by publishing a new general announcement.",
    confirmDeleteAnnouncement: "Are you sure you want to delete this announcement?",
    announcementDeletedSuccessfully: "Announcement deleted successfully",
    errorDeletingAnnouncement: "Error deleting announcement",
    unpin: "Unpin",
    pin: "Pin",
    unpinned: "Unpinned",
    announcementPinned: "Announcement pinned",

    // General
    fillAllRequiredFields: "Please fill all required fields",
    required: "Required",

    // Common Actions
    total: "Total",
    noContent: "No content",
    viewAll: "View All",
    typeMessage: "Type your message here...",
    attachedFiles: "Attached Files",
    attachFile: "Must attach file or write text",
    feedback: "Feedback",

    // Task & Grading
    taskSubmitted: "Submitted",
    taskGraded: "Graded",
    grade: "Grade",
    weight: "Weight",
    maxGrade: "Max Grade",
    evaluationFeedback: "Evaluation Feedback",
    noGradesYet: "No grades yet",
    errorLoadingTasks: "Error loading tasks",
    userNotFound: "User not found",
    newTaskAssigned: "New Task",

    // Project & Students
    activeProjects: "Active Projects",
    projectsCount: "Projects Count",
    noStudentsWithoutSupervisors: "No students without supervisors",
    calendar: "Calendar",
    departments: "Departments Management",
    selectProject: "Select Project",
    chooseProject: "Choose Project",

    // UI Text
    noProjectsAvailable: "No projects available",

    // Archive
    selectProjectDescription: "Select archived project to restore",

    // Supervisors
    addSupervisor: "Add Supervisor",
    addNewSupervisor: "Add New Supervisor",
    enterSupervisorData: "Enter supervisor data",
    jobNumber: "Job Number",
    enterJobNumber: "Enter job number",
    supervisorAddedSuccessfully: "Supervisor added successfully",
    errorAddingSupervisorAccount: "Error adding supervisor",
    supervisorsAndStudents: "Supervisors and Students",
    supervisorsAndStudentsManagement: "Academic Supervisors and Students Management",
    noSupervisorsYet: "No supervisors yet",
    startByAddingSupervisors: "Start by adding new supervisors",
    projectsManagement: "Projects Management",

    // Notifications, Departments, and Reports
    nothingToShow: "Nothing to show",
    departmentsManagement: "Departments Management",
    addDepartment: "Add Department",
    editDepartment: "Edit Department",
    deleteDepartment: "Delete Department",
    departmentCode: "Department Code",
    departmentNameAr: "Arabic Name",
    departmentNameEn: "English Name",
    departmentDescription: "Department Description",
    departmentActive: "Department Active",
    departmentInactive: "Department Inactive",
    noDepartments: "No departments",
    departmentAddedSuccessfully: "Department added successfully",
    departmentUpdatedSuccessfully: "Department updated successfully",
    departmentDeletedSuccessfully: "Department deleted successfully",
    errorAddingDepartment: "Error adding department",
    errorUpdatingDepartment: "Error updating department",
    errorDeletingDepartment: "Error deleting department",
    confirmDeleteDepartment: "Are you sure you want to delete this department?",
    addDepartmentDescription: "Add and edit academic departments",
    canStudentsRegister: "Students can register in this department",
    reportsAndStatistics: "Reports and Statistics",
    performanceReports: "Performance reports and statistics",
    generateReport: "Download Report",
    completionRate: "Completion Rate",
    completionRateDescription: "Percentage of completed projects out of total",
    averageProjectsPerSupervisor: "Average Projects per Supervisor",
    averageProjectsDescription: "Number of projects assigned to each supervisor",
    completedProjects: "Completed Projects",
    pendingProjects: "Pending Projects",
    totalSupervisors: "Total Supervisors",
    reportDate: "Report Date",
    generalStatistics: "General Statistics",
    reportInformation: "Report Information",
    additionalProjectDetails: "Additional project details",
    inactive: "Inactive",
    enabled: "Enabled",
    disabled: "Disabled",

    // Messages Page
    conversations: "Conversations",
    noConversations: "No conversations",
    noMessagesYet: "No messages yet",
    startConversation: "Start the conversation by sending a message",
    selectConversation: "Select a conversation",
    selectConversationToStart: "Select a conversation from the list to start messaging",
    writeMessage: "Write your message...",
    now: "Now",

    // Project Page Extra
    browseAvailableIdeas: "Browse Available Ideas",
    cannotSubmitNewIdea: "You cannot submit a new idea because you have an idea under review or approved",
    rejectionReasonLabel: "Rejection Reason",

    // Tasks Page Extra
    supervisorFilesForTask: "Supervisor Files for Task",
    submitTask: "Submit Task",
    editSubmission: "Edit Submission",
    taskPending: "Pending",

    // Coordinator Dashboard
    overviewAllProjects: "Comprehensive overview of all projects",
    totalProjectsCount: "Total Projects",
    activeProjectsCount: "Active Projects",
    completedProjectsCount: "Completed Projects",
    supervisorsCount: "Supervisors",
    studentsCount: "Students",
    averageOverallProgress: "Average Overall Progress",
    averageProgressDescription: "Average progress percentage for all active projects",
    activeProjectsLabel: "active project",
    needsFollowUp: "needs follow-up",
    successRate: "Success Rate",
    successRateDescription: "Percentage of completed projects out of total",
    outOf: "out of",
    recentProjectsLabel: "Recent Projects",
    recentProjectsDescription: "Latest projects registered in the system",
    noProjectsCurrently: "No projects currently",
    mostActiveSupervisors: "Most Active Supervisors",
    byProjectsAssigned: "By number of assigned projects",
    noSupervisorsCurrently: "No supervisors currently",

    // Projects Page
    noTitle: "Project without title",
    noDescription: "No description",
    awaitingApproval: "Awaiting Approval",
    stopped: "Stopped",
    unknown: "Unknown",
    progressLabel: "Progress",
    startDateLabel: "Start Date:",
    endDateLabel: "End Date:",
    supervisorLabel: "Supervisor:",
    departmentLabel: "Department:",
    studentLabel: "Student:",
    fillRequiredFields: "Please fill all required fields",
    errorLoadingProjectsMsg: "Error loading projects",
    projectAcceptedSuccess: "Project accepted successfully",
    projectRejectedMsg: "Project rejected",
    projectStoppedMsg: "Project stopped temporarily",
    projectArchivedMsg: "Project archived",
    errorAcceptingProject: "Error accepting project",
    errorRejectingProjectMsg: "Error rejecting project",
    errorStoppingProject: "Error stopping project",
    errorArchivingProjectMsg: "Error archiving project",
    projectAddedSuccess: "Project added successfully",
    projectUpdatedSuccess: "Project updated successfully",
    projectDeletedMsg: "Project deleted",
    errorAddingProjectMsg: "Error adding project",
    errorUpdatingProjectMsg: "Error updating project",
    errorDeletingProjectMsg: "Error deleting project",
    studentAddedToProjectSuccess: "Student added to project successfully",
    studentRemovedFromProject: "Student removed from project",
    studentAlreadyHasProjectMsg: "This student already has a project",
    errorAddingStudentMsg: "Error adding student",
    errorRemovingStudentMsg: "Error removing student",
    errorLoadingTeamMembersMsg: "Error loading team members",
    pleaseSelectStudentMsg: "Please select a student",
    ideaDataLoadedMsg: "Approved idea data loaded, please select a supervisor",
    errorLoadingIdeaDataMsg: "Error loading idea data",

    // Supervisors Page
    addSupervisorBtn: "Add Supervisor",
    addStudentBtn: "Add Student",
    addNewSupervisorTitle: "Add New Supervisor",
    enterSupervisorDataDesc: "Enter academic supervisor data",
    addNewStudentTitle: "Add New Student",
    enterStudentDataDesc: "Enter student data",
    fullNameLabel: "Full Name",
    jobNumberLabel: "Job Number",
    phoneNumberLabel: "Phone Number",
    passwordLabel: "Password",
    enterPasswordPlaceholder: "Enter password",
    emailLabel: "Email",
    departmentSelectLabel: "Department",
    selectDepartmentPlaceholder: "Select Department",
    loadingText: "Loading...",
    cancelBtn: "Cancel",
    addBtn: "Add",
    supervisorAddedSuccess: "Supervisor added successfully",
    emailAlreadyInUseMsg: "Email already in use",
    errorAddingSupervisorMsg: "Error adding supervisor",
    studentAddedSuccess: "Student added successfully",
    errorAddingStudentAccountMsg: "Error adding student",
    noSupervisorsYetMsg: "No supervisors yet",
    startAddingSupervisors: "Start by adding new supervisors",
    projectsCountLabel: "Projects Count",
    projectWord: "project",
    noStudentsYetMsg: "No students yet",
    studentsWillAppear: "Students will appear here after registration",
    universityIdLabel: "University ID",

    // Students Page
    studentsManagementTitle: "Students Management",
    assignSupervisorsDesc: "Assign supervisors to students and track their status",
    addNewStudentBtn: "Add New Student",
    totalStudentsLabel: "Total Students",
    studentsWithoutSupervisorLabel: "Students Without Supervisor",
    studentsWithSupervisorLabel: "Students With Supervisor",
    studentsListTitle: "Students List",
    studentsListDesc: "All registered students in the system",
    assignedStatus: "Assigned",
    withoutSupervisorStatus: "Without Supervisor",
    changeSupervisorBtn: "Change Supervisor",
    assignSupervisorBtn: "Assign Supervisor",
    assignSupervisorTitle: "Assign Supervisor",
    selectSupervisorForStudent: "Select the appropriate supervisor for the student",
    supervisorSelectLabel: "Supervisor",
    selectSupervisorPlaceholder: "Select Supervisor",
    studentWord: "student",
    selectedSupervisorLabel: "Selected Supervisor:",
    currentStudentsCountLabel: "Current Students Count:",
    assignBtn: "Assign",
    supervisorAssignedSuccess: "Supervisor assigned successfully",
    errorAssigningSupervisorMsg: "Error assigning supervisor",
    selectSupervisorMsg: "Please select a supervisor",
    confirmChangeSupervisor: "Confirm Change Supervisor",
    studentLinkedToProject: "This student is already linked to a project or supervisor.",
    studentName: "Student:",
    currentSupervisorLabel: "Current Supervisor:",
    newSupervisorLabel: "New Supervisor:",
    teamUpdateWarning: "Warning: This student has a linked project. Upon confirmation, the project supervisor will be changed and all team members will be updated.",
    confirmChangeQuestion: "Are you sure you want to change the supervisor?",
    confirmBtn: "Confirm Change",
    notSpecifiedText: "Not specified",
    noSupervisorText: "None",
    errorLoadingDataMsg: "Error loading data",

    // Pending Invites
    pendingInvite: "pending invite",
    pendingInvites: "pending invites",
    teamApprovalPending: "You have team join requests awaiting your approval",

    // Total Grade
    totalGrade: "Total Grade",
    YourOverallGrade: "Your overall grade",

    //team approval page
    reviewPendingInvites: "Review pending team invites",
    noPendingInvites: "No pending invites",
    approveInvite: "Approve Invite",
    rejectInvite: "Reject Invite",
    teamInvites: "Team Project Invites",
    errorLoadingInvites: "An error occurred while loading the invites",
    inviteApproved: "You have successfully joined the project",
    inviteRejected: "The invitation has been rejected",
    errorApproving: "An error occurred while approving the invitation",
    errorRejecting: "An error occurred while rejecting the invitation",
    browseProjectIdeas: "Browse Project Ideas",


    //calendar psage  
    calendarSubtitle: "All tasks and meetings in one place",
    upcomingEvents: "Upcoming Events",
    noUpcomingEvents: "No upcoming events",
    noEventsForSelectedDate: "No events for the selected date",
    events: "Events",
    colorLegend: "Color Legend",
    submitted: "Submitted",
    graded: "Graded",

    //monthes & days
      january: "January",
      february: "February",
      march: "March",
      april: "April",
      may: "May",
      june: "June",
      july: "July",
      august: "August",
      september: "September",
      october: "October",
      november: "November",
      december: "December",
      sunday: "Sunday",
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",

      //messages page
      searchPlaceholder: "Search...",
      selectConversationInstructions: "Select a conversation from the list to start messaging",
      writeYourMessage: "Write your message...",
      userFallbackName:"User",
      noMessagesYetText:"No messages yet. Start the conversation by sending a message.",
      errorSendingMessageMsg:"An error occurred while sending the message",

      //project idea page
      youHaveActiveProjectIdea:"You have a project idea under review or approved",
      errorCheckingSubmissionEligibility:"An error occurred while checking submission eligibility",
      errorLoadingDepartments:"An error occurred while loading departments",
      shouldBeAtLeastTwoStudents:"There should be at least two students in the project",
      gpaMustNotExceed4:"GPA must not exceed 4.00",
      pleaseSelectProjectDepartment:"Please select project department",
      departmentNotValid:"Project department is not valid",
      pleaseCompleteStudentInfo:"Please complete all students' information",
      pleaseSelectStudentDepartment:"Please select student department",
      pleaseAcceptPlagiarismDeclaration:"You must accept the plagiarism declaration",
      studentAlreadyInAnotherProject:"Cannot submit idea: Student ",
      alreadyInAnotherProject:" is already in another project under review or approved",
      haveActiveProject:" already has an active project",
      newProjectIdea:"New Project Idea",
      studentSubmittedNewProjectIdea:"Student ",
      projectTeamInvitation:"Invitation to Join Project",
      youHaveBeenInvitedToJoinProject:"You have been invited to join a project",
      by: " by ",
      pleaseReviewAndAcceptTheInvitation: "Please review and accept the invitation to join the project team.",
      projectIdeaSubmittedSuccessfully:"Project idea submitted successfully! Invitations have been sent to team members.",
      errorSubmittingProjectIdea:"An error occurred while submitting the project idea",
      checkingProjectStatus:"Checking...",
      submitYourGraduationProjectIdea:"Submit your graduation project idea",
      youCannotSubmitNewIdeaCurrently:"You cannot submit a new idea currently. You have an idea under review or approved.",
      Note:"Note:",
      afterSubmittingProjectIdea:"All projects must be team-based (at least 2 students). After review, all members must approve the idea and participate.",
      basicInformation:"Basic Information",
      basicInformationDescription:"General information about the project and program",
      program: "Program",
      egComputerScience:"e.g., Bachelor of Computer Science",
      academicYear: "Academic Year",
      egAcademicYear:"e.g., 2024-2025",
      semester: "Semester",
      selectSemester:"Select Semester",
      firstSemester: "First Semester",
      secondSemester: "Second Semester",
      selectProjectType:"Select Project Type",
      oneCourse: "One Semester Project",
      twoCourses: "Two Semesters Project",
      studentsInformation:"Students Information",
      studentsInformationDescription:"Information of all team members (at least 2)",
      gpa:"GPA",
      supervisorInformation:"Supervisor Information",
      supervisorDescription:"Main supervisor and co-supervisor (if any) details",
      supervisorName:"Supervisor Name",
      supervisorEmail:"Supervisor Email (UoB)",
      coSupervisorName:"Co-Supervisor Name (if any)",
      coSupervisorEmail:"Co-Supervisor Email",
      projectDetailsDescription:"Comprehensive description of the project and its objectives",
      problemStatement:"Problem Statement",
      significance:"Significance of the Project",
      literatureReview:"Brief Literature Review",
      references:"Supporting References",
      projectTimeline:"Project Timeline",
      projectTimelineDescription:"Proposed timeline for the project",
      plagiarismDeclaration:"Plagiarism Declaration",
      plagiarismDeclarationDescription:"You must agree to the declaration to submit the project",
      plagiarismDeclarationLabel:"I declare that this work is my own and that all references and sources used have been properly cited.",
      submitting:"Submitting...",
      submitIdea:"Submit Idea",
      requirementCollection: "Requirement Collection",  
      design: "Design",
      implementation: "Implementation",
      testingAndResults: "Testing and Results",
      reportWriting: "Report Writing",
      presentation: "Presentation",
      phase: "Phases",

      //ideas page
      errorLodingProjectIdeas: "Error loading project ideas",
      notFoundIdea: "Project idea not found",
      errorLoadingIdeasInfo: "Error loading idea details",
      ideaSelectedByMe: "You have selected this idea",
      ideaTakenByOtherStudent: "This idea has been taken by another student",
      youCannotPickAnotherIdea: "You cannot select another idea. You already have a selected idea.",
      ideaSelectedSuccessfully: "Idea selected successfully!",
      userNotFoundInDatabase: "Your account is not found in the database",
      errorSelectingIdea: "Error occurred while selecting the idea",
      available: "Available",
      takenByOtherStudent: "Taken",
      selected: "Selected",
      noIdeaSelected: "No idea has been selected yet",
      browseAndSelectProjectIdeasDescription: "Browse and select from the project ideas proposed by supervisors (only one idea can be selected)",
      mySelectedIdea: "My Selected Idea",
      mySelectedIdeaDescription: "Shows the idea you have selected (if any)",
      noIdeaSelectedYet: "You have not selected any idea yet. Browse the available ideas and choose one to start your project.",
      availableIdeas: "Available Ideas",
      availableIdeasDescription: "Idea available for selection",
      noAvailableIdeasCurrently: "No ideas are currently available",
      noAvailableIdeasDescription: "No available ideas have been proposed by supervisors yet",
      ideaDetails: "Proposed Project Idea Details",
      technologiesUsed: "Technologies Used",
      projectOption: "Project Option",
      selecting: "Selecting...",
      youHaveAlreadySelectedAnIdea: "You already have a selected idea",
      ideaNotAvailable: "This idea is taken",
      selectThisIdea: "Select this idea",

      //coordinate project page
      TemporarySuspension: "Temporary Suspension",
      activateProject: "Activate",
      addNewProject: "Add New Project",
      enterProjectDetailsAndAssignSupervisorAndStudent: "Enter project details and assign a supervisor and student",
      enterProjectTitle: "Enter project title",
      enterProjectDescription: "Enter project description",
      projectStartDate: "Project start date",
      projectEndDate: "Project end date (optional)",
      selectSupervisor: "Select supervisor",
      stu: "Student (optional)",
      selectStudent: "Select student",
      noStudent: "No student",
      addProj: "Add project",
      searchProjects: "Search projects...",
      noMatchingResults: "No matching results",
      startAddingProjects: "Start adding new projects",

      // coordinator supervisor page
      pleaseFillAllRequiredFields: "Please fill all required fields",
      errorAddingSupervisor: "An error occurred while adding the supervisor",
      studentAdded: "Student added successfully",
      manageSupervisorsAndStudents: "Manage supervisors and students",
      enterSupervisorDetails: "Enter supervisor details",
      egDrAhmedMohamed: "e.g. Dr. Ahmed Mohamed",
      supervisorId: "Employee ID",
      egEMP12345: "e.g. EMP12345",
      enterSupervisorId: "Enter employee ID",
      chooseDepartment: "Select department",
      enterStudentDetails: "Enter student details",
      egAhmedMohamed: "e.g. Ahmed Mohamed",
      addNewSupervisors: "Start adding new supervisors",
      numberOfProjects: "Number of projects",
      addNewStudents: "Start adding new students",

      // coordinate students page
      None: "None",
      manageStudents: "Manage Students",
      assignSupervisorsAndTrackStudents: "Assign supervisors to students and track their status",
      studentsWillAppearAfterRegistration: "Students will appear here after registration",
      allStudentsInSystem: "All registered students in the system",
      noSupervisor: "No Supervisor",
      studentAlreadyAssignedToProjectOrSupervisor: "This student is already assigned to a project or a supervisor.",
      alertStudentHasProjectLinked: "Warning: This student is linked to a project. Confirming will change the project supervisor and update all team members.",
      AreYouSureYouWantToChangeTheSupervisor: "Are you sure you want to change the supervisor?",
      YesChange: "Yes, change",
      addNewStudentDescription: "Enter student details to create a new account",
      enterStudentId: "Example: 202012345",
      addDepartmentsFromManagementPage: "Please add departments from the department management page",
      enterPhone: "Example: 39335681",

      //coordinate departments page
      errorSavingDepartment: "An error occurred while saving the department",
      manageDepartments: "Manage Departments",
      AddAndEditAcademicDepartments: "Add and Edit Academic Departments",
      addNewDepartmentInstructions: "Start by adding a new academic department",
      addNewDepartment: "Add New Department",
      updateDepartmentInfo: "Update Department Information",
      enterNewDepartmentInfo: "Enter the new department information",
      departmentCodeLabel: "Department Code",
      egCS: "e.g., cs, it, is",
      egDepartmentName: "e.g., علوم الحاسب",
      egDepartmentNameEn: "e.g., Computer Science",
      departmentDescriptionPlaceholder: "Short description of the department",
      isActiveDepartment: "Department is Active",
      departmentCanBeSelectedByStudents: "Students can enroll in this department",
      theCode:"Department code",

      //coordinate messages page
      user: "User",
      NoMessagesYet: "No messages yet",
      errorLoadingConversations: "An error occurred while loading conversations",
      errorSendingMessage: "An error occurred while sending the message",
      searchByName: "Search by name...",
      NoMessages: "No messages",
      message: "Message",
      forSending: "to send",
      forNewLine: "for a new line",
      chooseConversation: "Choose a conversation",
      chooseConversationDescription: "Select a conversation from the list to start messaging",
      messagesm: "Conversations",

      //coordinate announcements page
      announcementPinnedSuccessfully: "Announcement pinned successfully",
      announcementUnpinnedSuccessfully: "Announcement unpinned successfully",
      AnErrorOccurred: "An error occurred",
      singleSemesterProject: "Single-Semester Projects",
      twoSemesterProjects: "Two-Semester Projects",
      manageAndPublishGeneralAnnouncements: "Manage and publish general announcements for all users",
      publishNewGeneralAnnouncement: "Publish a new general announcement",
      selectAnnouncementScopeDescription: "Select the target audience for the announcement",
      announcementWillBePinnedToTopOfList: "The announcement will appear at the top of the list",
      noAnnouncementsDescription: "No announcements have been published yet. Start by publishing a new general announcement.",

      //coordinate reports page
      graduationProjectsReport: "Graduation-Projects-Report-",
      reportsDescription: "Statistics and performance reports",
      downloadReport: "Download Report",
      totalProjects: "Total Projects",
      supervisorsNumber: "Number of Supervisors",
      studentsNumber: "Number of Students",
      reportDetails: "Report Details",
      reportDetailsDescription: "Additional details about the projects",
      projectsPerSupervisor: "Average Projects per Supervisor",
      projectsPerSupervisorDescription: "Number of projects assigned to each supervisor",
      graduationProjectsReportTitle: "Graduation Projects Report",

  },
}
